# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="کد قالب"
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=255, verbose_name="قالب عنوان"),
                ),
                ("body_template", models.TextField(verbose_name="قالب متن")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("push", "پوش"),
                            ("in_app", "درون برنامه"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="کانال",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "قالب اعلان",
                "verbose_name_plural": "قالب های اعلان",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "ایمیل"),
                            ("sms", "پیامک"),
                            ("push", "پوش"),
                            ("in_app", "درون برنامه"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "کم"), ("normal", "عادی"), ("high", "بالا")],
                        default="normal",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("scheduled", "زمان بندی شده"),
                            ("sent", "ارسال شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان زمان بندی"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرندگان",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان ها",
            },
        ),
    ]
