# Generated by Django 6.0.3 on 2026-04-04 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("review", "در انتظار بازبینی"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/covers/%Y/%m/%d/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان فارسی"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                (
                    "excerpt_fa",
                    models.TextField(blank=True, verbose_name="خلاصه کوتاه فارسی"),
                ),
                (
                    "excerpt_en",
                    models.TextField(blank=True, verbose_name="خلاصه کوتاه انگلیسی"),
                ),
                (
                    "summary_fa",
                    models.TextField(blank=True, verbose_name="خلاصه فارسی"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="خلاصه انگلیسی"),
                ),
                ("content_fa", models.TextField(blank=True, verbose_name="متن فارسی")),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="متن انگلیسی"),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="زمان مطالعه (دقیقه)"
                    ),
                ),
                (
                    "meta_title_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان متا فارسی"
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان متا انگلیسی"
                    ),
                ),
                (
                    "meta_description_fa",
                    models.TextField(blank=True, verbose_name="توضیحات متا فارسی"),
                ),
                (
                    "meta_description_en",
                    models.TextField(blank=True, verbose_name="توضیحات متا انگلیسی"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="تعداد بازدید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان حذف نرم"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"type": "category"},
                        related_name="posts_as_category",
                        to="taxonomy.term",
                        verbose_name="دسته ها",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"type": "tag"},
                        related_name="posts_as_tag",
                        to="taxonomy.term",
                        verbose_name="برچسب ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="news_post_status_29dd9a_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="news_post_is_feat_7c29c5_idx"
                    ),
                ],
            },
        ),
    ]
