# Generated by Django 5.2.8 on 2026-04-05 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_fix_missing_cover_image_column"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTrendingTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "label_fa",
                    models.CharField(max_length=120, verbose_name="برچسب فارسی"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="برچسب انگلیسی"
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=0, verbose_name="وزن")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "عبارت ترند اخبار",
                "verbose_name_plural": "عبارات ترند اخبار",
                "ordering": ["-weight", "id"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_live",
            field=models.BooleanField(default=False, verbose_name="خبر زنده"),
        ),
        migrations.CreateModel(
            name="PostBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="news.post",
                        verbose_name="خبر",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشانک خبر",
                "verbose_name_plural": "نشانک های خبر",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "post"), name="unique_post_bookmark"
                    )
                ],
            },
        ),
    ]
