# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_path",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="مسیر مبدا"
                    ),
                ),
                ("to_path", models.CharField(max_length=255, verbose_name="مسیر مقصد")),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        default=301, verbose_name="کد وضعیت"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
            ],
            options={
                "verbose_name": "قانون ریدایرکت",
                "verbose_name_plural": "قوانین ریدایرکت",
            },
        ),
        migrations.CreateModel(
            name="SeoRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(max_length=255, verbose_name="الگوی مسیر"),
                ),
                (
                    "title_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="الگوی عنوان"
                    ),
                ),
                (
                    "description_template",
                    models.TextField(blank=True, verbose_name="الگوی توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="اولویت"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_rules",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "قانون سئو",
                "verbose_name_plural": "قوانین سئو",
            },
        ),
        migrations.CreateModel(
            name="SeoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه محتوا"),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=255, verbose_name="عنوان متا"),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="لینک canonical"),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان OG"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="توضیحات OG"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/og/%Y/%m/%d/",
                        verbose_name="تصویر OG",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        default="index,follow",
                        max_length=120,
                        verbose_name="دستور robots",
                    ),
                ),
                (
                    "include_in_sitemap",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در سایت\u200cمپ"
                    ),
                ),
                (
                    "changefreq",
                    models.CharField(
                        default="weekly", max_length=16, verbose_name="تناوب تغییر"
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=3,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "lastmod",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آخرین تغییر"
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="داده ساختاریافته"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_meta_records",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیکربندی سئو",
                "verbose_name_plural": "پیکربندی\u200cهای سئو",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "language"),
                        name="uq_seoconfig_content_lang",
                    )
                ],
            },
        ),
    ]
