# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه محتوا"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="زمان برنامه ریزی")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("done", "انجام شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان اجرا"
                    ),
                ),
                (
                    "celery_task_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام تسک Celery Beat"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publish_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه انتشار",
                "verbose_name_plural": "برنامه های انتشار",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="publishing__status_d7a622_idx",
                    )
                ],
            },
        ),
    ]
