# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام کلاینت")),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("frontend", "فرانت اند"),
                            ("internal", "داخلی"),
                            ("partner", "همکار"),
                        ],
                        default="frontend",
                        max_length=20,
                        verbose_name="نوع کلاینت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "allowed_origins",
                    models.JSONField(
                        blank=True, default=list, verbose_name="مبداهای مجاز"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="api_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالک ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاینت API",
                "verbose_name_plural": "کلاینت های API",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(max_length=20, verbose_name="پیشوند کلید"),
                ),
                (
                    "hashed_key",
                    models.CharField(max_length=255, verbose_name="کلید هش شده"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انقضا"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین استفاده"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="api.apiclient",
                        verbose_name="کلاینت",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلید API",
                "verbose_name_plural": "کلیدهای API",
            },
        ),
        migrations.CreateModel(
            name="ApiRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="default", max_length=120, verbose_name="دامنه"
                    ),
                ),
                (
                    "limit_per_minute",
                    models.PositiveIntegerField(
                        default=60, verbose_name="محدودیت در دقیقه"
                    ),
                ),
                (
                    "limit_per_day",
                    models.PositiveIntegerField(
                        default=10000, verbose_name="محدودیت روزانه"
                    ),
                ),
                (
                    "burst_limit",
                    models.PositiveIntegerField(
                        default=30, verbose_name="حداکثر لحظه ای"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to="api.apiclient",
                        verbose_name="کلاینت",
                    ),
                ),
            ],
            options={
                "verbose_name": "محدودیت نرخ API",
                "verbose_name_plural": "محدودیت های نرخ API",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "scope"), name="uq_client_scope_rate"
                    )
                ],
            },
        ),
    ]
