# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=160, verbose_name="اسلاگ")),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tag", "برچسب"),
                            ("category", "دسته بندی"),
                            ("topic", "موضوع"),
                        ],
                        max_length=16,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("news", "خبر"),
                            ("weapon", "تسلیحات"),
                            ("martyr", "شهدا"),
                            ("document", "مستندات"),
                            ("global", "عمومی"),
                        ],
                        default="global",
                        max_length=20,
                        verbose_name="دامنه",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="taxonomy.term",
                        verbose_name="والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "ترم",
                "verbose_name_plural": "ترم\u200cها",
                "ordering": ["type", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type", "slug"), name="uq_term_type_slug"
                    )
                ],
            },
        ),
    ]
