# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("post", "خبر"),
                            ("weapon", "تسلیح"),
                            ("martyr", "شهید"),
                            ("document", "مستند"),
                        ],
                        max_length=20,
                        verbose_name="نوع منبع",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه منبع"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("excerpt", models.TextField(blank=True, verbose_name="خلاصه")),
                ("body", models.TextField(blank=True, verbose_name="متن")),
                (
                    "category",
                    models.CharField(blank=True, max_length=120, verbose_name="دسته"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="برچسب ها"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="عمومی")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_documents",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند جستجو",
                "verbose_name_plural": "اسناد جستجو",
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id", "language"],
                        name="search_inde_source__fadb47_idx",
                    ),
                    models.Index(
                        fields=["is_public", "published_at"],
                        name="search_inde_is_publ_b4cff5_idx",
                    ),
                ],
            },
        ),
    ]
