# Generated by Django 5.2.8 on 2026-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "label_fa",
                    models.CharField(max_length=120, verbose_name="عبارت فارسی"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="عبارت انگلیسی"
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=0, verbose_name="وزن")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "عبارت جستجوی پرطرفدار",
                "verbose_name_plural": "عبارات جستجوی پرطرفدار",
                "ordering": ["-weight", "id"],
            },
        ),
    ]
