# Generated by Django 5.2.8 on 2026-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_index", "0002_popularsearchterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularsearchterm",
            name="term_type",
            field=models.CharField(
                choices=[("news", "ترند اخبار"), ("search", "جستجوی محبوب")],
                default="search",
                max_length=16,
                verbose_name="نوع عبارت",
            ),
        ),
    ]
