# Generated by Django 6.0.3 on 2026-04-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("review", "در انتظار بازبینی"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievements/covers/%Y/%m/%d/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان فارسی"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                (
                    "excerpt_fa",
                    models.TextField(blank=True, verbose_name="خلاصه کوتاه فارسی"),
                ),
                (
                    "excerpt_en",
                    models.TextField(blank=True, verbose_name="خلاصه کوتاه انگلیسی"),
                ),
                (
                    "summary_fa",
                    models.TextField(blank=True, verbose_name="خلاصه فارسی"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="خلاصه انگلیسی"),
                ),
                ("content_fa", models.TextField(blank=True, verbose_name="متن فارسی")),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="متن انگلیسی"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("drone", "پهپاد"),
                            ("missile", "موشک"),
                            ("aircraft", "هواپیما"),
                            ("ship", "کشتی"),
                            ("infrastructure", "زیرساخت"),
                        ],
                        default="drone",
                        max_length=32,
                        verbose_name="نوع هدف",
                    ),
                ),
                (
                    "region_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="منطقه فارسی"
                    ),
                ),
                (
                    "region_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="منطقه انگلیسی"
                    ),
                ),
                (
                    "destroyed_targets_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد اهداف نابود شده"
                    ),
                ),
                (
                    "strategic_gain_count",
                    models.PositiveIntegerField(default=0, verbose_name="شاخص دستاورد"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("official", "رسمی"),
                            ("documented", "مستند"),
                            ("claimed", "ادعایی"),
                        ],
                        default="documented",
                        max_length=16,
                        verbose_name="وضعیت تایید",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="تعداد بازدید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "دستاورد",
                "verbose_name_plural": "دستاوردها",
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="achievement_status_db81a7_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="achievement_is_feat_6d6634_idx"
                    ),
                ],
            },
        ),
    ]
