# Generated by Django 5.2.8 on 2026-04-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
        ("martyrs", "0002_martyr_meta_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="martyr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_achievements",
                to="martyrs.martyr",
                verbose_name="شهید مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="meta_description_en",
            field=models.TextField(blank=True, verbose_name="توضیحات متا انگلیسی"),
        ),
        migrations.AddField(
            model_name="achievement",
            name="meta_description_fa",
            field=models.TextField(blank=True, verbose_name="توضیحات متا فارسی"),
        ),
        migrations.AddField(
            model_name="achievement",
            name="meta_title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان متا انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="meta_title_fa",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان متا فارسی"
            ),
        ),
    ]
