// Mock Data for VoiceIran Dashboard
import type {
  User,
  Role,
  AccessProfile,
  Post,
  Category,
  Tag,
  Weapon,
  WeaponCategory,
  Martyr,
  MartyrCategory,
  Document,
  DocumentCategory,
  Achievement,
  AchievementCategory,
  SiteSettings,
  OrganizationProfile,
  LiveStat,
  Banner,
  StaticPage,
  Notification,
  PublishSchedule,
  SeoConfig,
  RedirectRule,
  ApiClient,
  ApiRateLimit,
  AnalyticsDashboard,
  LanguageSetting,
  VisitStats,
} from '@/lib/types'

// Helper to generate Persian dates (Jalali)
const jalaliDates = [
  '۱۴۰۳/۱۲/۱۵',
  '۱۴۰۳/۱۲/۱۰',
  '۱۴۰۳/۱۲/۰۵',
  '۱۴۰۳/۱۱/۲۸',
  '۱۴۰۳/۱۱/۲۰',
  '۱۴۰۳/۱۱/۱۵',
  '۱۴۰۳/۱۱/۱۰',
  '۱۴۰۳/۱۱/۰۵',
]

// Mock Roles
export const mockRoles: Role[] = [
  {
    id: '1',
    name: 'مدیر ارشد',
    codename: 'superadmin',
    permissions: [],
    userCount: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'مدیر محتوا',
    codename: 'content_manager',
    permissions: [],
    userCount: 5,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'ویراستار',
    codename: 'editor',
    permissions: [],
    userCount: 12,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'بازدیدکننده',
    codename: 'viewer',
    permissions: [],
    userCount: 25,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

export const mockAccessProfiles: AccessProfile[] = [
  {
    id: '1',
    name: 'پروفایل سردبیر',
    description: 'دسترسی کامل به اخبار، طبقه‌بندی و زمان‌بندی انتشار',
    roleId: '2',
    canPublish: true,
    canDelete: true,
    canManageUsers: false,
    canViewAudit: true,
    allowedApps: ['news', 'publishing', 'taxonomy', 'seo'],
    deniedApps: ['accounts'],
    customPermissions: {},
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'پروفایل ناظر',
    description: 'مشاهده محتوا و گزارش‌ها بدون ویرایش',
    roleId: '4',
    canPublish: false,
    canDelete: false,
    canManageUsers: false,
    canViewAudit: false,
    allowedApps: ['news', 'arsenal', 'martyrs', 'documents', 'achievements', 'analytics'],
    deniedApps: [],
    customPermissions: {},
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@voiceiran.ir',
    phone: '+989121111111',
    firstName: 'محمد',
    lastName: 'احمدی',
    fullName: 'محمد احمدی',
    avatar: '/placeholder.svg?height=40&width=40',
    role: mockRoles[0],
    roles: [mockRoles[0]],
    isActive: true,
    isStaff: true,
    isSuperuser: true,
    lastLogin: '2024-03-10T08:30:00Z',
    dateJoined: '2023-01-01T00:00:00Z',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-10T08:30:00Z',
  },
  {
    id: '2',
    username: 'content_manager',
    email: 'manager@voiceiran.ir',
    phone: '+989122222222',
    firstName: 'علی',
    lastName: 'رضایی',
    fullName: 'علی رضایی',
    avatar: '/placeholder.svg?height=40&width=40',
    role: mockRoles[1],
    roles: [mockRoles[1]],
    isActive: true,
    isStaff: true,
    isSuperuser: false,
    lastLogin: '2024-03-09T14:20:00Z',
    dateJoined: '2023-03-15T00:00:00Z',
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2024-03-09T14:20:00Z',
  },
  {
    id: '3',
    username: 'editor1',
    email: 'editor1@voiceiran.ir',
    phone: '+989123333333',
    firstName: 'فاطمه',
    lastName: 'محمدی',
    fullName: 'فاطمه محمدی',
    avatar: '/placeholder.svg?height=40&width=40',
    role: mockRoles[2],
    roles: [mockRoles[2]],
    isActive: true,
    isStaff: true,
    isSuperuser: false,
    lastLogin: '2024-03-10T10:15:00Z',
    dateJoined: '2023-06-01T00:00:00Z',
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2024-03-10T10:15:00Z',
  },
]

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'اخبار نظامی',
    nameEn: 'Military News',
    slug: 'military-news',
    description: 'آخرین اخبار نظامی و دفاعی',
    parent: null,
    order: 1,
    isActive: true,
    postCount: 45,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'فناوری دفاعی',
    nameEn: 'Defense Technology',
    slug: 'defense-technology',
    description: 'پیشرفت‌های فناوری در حوزه دفاعی',
    parent: null,
    order: 2,
    isActive: true,
    postCount: 32,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'رویدادها',
    nameEn: 'Events',
    slug: 'events',
    description: 'رویدادها و مراسم‌های رسمی',
    parent: null,
    order: 3,
    isActive: true,
    postCount: 28,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'بین‌الملل',
    nameEn: 'International',
    slug: 'international',
    description: 'اخبار بین‌المللی نظامی',
    parent: null,
    order: 4,
    isActive: true,
    postCount: 19,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
]

// Mock Tags
export const mockTags: Tag[] = [
  { id: '1', name: 'سپاه', nameEn: 'IRGC', slug: 'irgc', postCount: 56, createdAt: '2023-01-01T00:00:00Z' },
  { id: '2', name: 'ارتش', nameEn: 'Army', slug: 'army', postCount: 42, createdAt: '2023-01-01T00:00:00Z' },
  { id: '3', name: 'موشک', nameEn: 'Missile', slug: 'missile', postCount: 38, createdAt: '2023-01-01T00:00:00Z' },
  { id: '4', name: 'پهپاد', nameEn: 'Drone', slug: 'drone', postCount: 34, createdAt: '2023-01-01T00:00:00Z' },
  { id: '5', name: 'دفاع هوایی', nameEn: 'Air Defense', slug: 'air-defense', postCount: 29, createdAt: '2023-01-01T00:00:00Z' },
]

// Mock Posts
export const mockPosts: Post[] = [
  {
    id: '1',
    type: 'news',
    title: 'رونمایی از سامانه جدید دفاع هوایی باور ۳۷۳',
    titleEn: 'Unveiling of new Bavar 373 air defense system',
    slug: 'bavar-373-new-system',
    excerpt: 'وزارت دفاع از نسخه جدید سامانه دفاع هوایی باور ۳۷۳ رونمایی کرد که دارای قابلیت‌های پیشرفته‌تری است.',
    content: '<p>در مراسمی با حضور وزیر دفاع، نسخه جدید سامانه دفاع هوایی باور ۳۷۳ رونمایی شد...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '1', username: 'admin', fullName: 'محمد احمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [mockCategories[1]],
    tags: [mockTags[4]],
    viewCount: 12500,
    publishedAt: '2024-03-10T10:00:00Z',
    createdAt: '2024-03-10T08:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
    isBreaking: true,
    isFeatured: true,
    isLive: false,
    summary: 'رونمایی از نسخه ارتقا یافته باور ۳۷۳ با قابلیت‌های جدید',
    readingTimeMinutes: 6,
  },
  {
    id: '2',
    type: 'news',
    title: 'برگزاری رزمایش مشترک نیروهای مسلح در خلیج فارس',
    titleEn: 'Joint military exercise in Persian Gulf',
    slug: 'persian-gulf-exercise',
    excerpt: 'رزمایش مشترک نیروی دریایی ارتش و سپاه در آب‌های خلیج فارس برگزار شد.',
    content: '<p>رزمایش مشترک با هدف ارتقای آمادگی دفاعی در منطقه برگزار شد...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '2', username: 'content_manager', fullName: 'علی رضایی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [mockCategories[0]],
    tags: [mockTags[0], mockTags[1]],
    viewCount: 8900,
    publishedAt: '2024-03-09T14:00:00Z',
    createdAt: '2024-03-09T12:00:00Z',
    updatedAt: '2024-03-09T14:00:00Z',
    isBreaking: false,
    isFeatured: true,
    isLive: false,
    summary: 'رزمایش مشترک ارتش و سپاه در خلیج فارس',
    readingTimeMinutes: 5,
  },
  {
    id: '3',
    type: 'news',
    title: 'تولید انبوه پهپاد شاهد ۱۳۶ آغاز شد',
    titleEn: 'Mass production of Shahed 136 drone begins',
    slug: 'shahed-136-production',
    excerpt: 'خط تولید انبوه پهپاد شاهد ۱۳۶ با ظرفیت بالا افتتاح شد.',
    content: '<p>با افتتاح خط تولید جدید، ظرفیت تولید پهپادهای شاهد افزایش یافت...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'pending_review',
    author: { id: '3', username: 'editor1', fullName: 'فاطمه محمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [mockCategories[1]],
    tags: [mockTags[3]],
    viewCount: 0,
    createdAt: '2024-03-10T09:00:00Z',
    updatedAt: '2024-03-10T09:30:00Z',
    isBreaking: false,
    isFeatured: false,
    isLive: true,
    summary: 'افتتاح خط تولید انبوه پهپاد شاهد ۱۳۶',
    readingTimeMinutes: 4,
  },
  {
    id: '4',
    type: 'news',
    title: 'دیدار فرمانده کل سپاه با رهبر انقلاب',
    titleEn: 'Meeting of IRGC commander with Supreme Leader',
    slug: 'irgc-commander-meeting',
    excerpt: 'فرمانده کل سپاه در دیدار با رهبر انقلاب گزارشی از آمادگی نیروها ارائه داد.',
    content: '<p>در این دیدار آخرین وضعیت آمادگی نیروهای سپاه بررسی شد...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'draft',
    author: { id: '3', username: 'editor1', fullName: 'فاطمه محمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [mockCategories[2]],
    tags: [mockTags[0]],
    viewCount: 0,
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-10T11:00:00Z',
    isBreaking: false,
    isFeatured: false,
    isLive: false,
    summary: 'دیدار فرمانده کل سپاه با رهبر انقلاب',
    readingTimeMinutes: 5,
  },
  {
    id: '5',
    type: 'news',
    title: 'همکاری دفاعی ایران و روسیه گسترش می‌یابد',
    titleEn: 'Iran-Russia defense cooperation expands',
    slug: 'iran-russia-cooperation',
    excerpt: 'توافقات جدید دفاعی میان ایران و روسیه امضا شد.',
    content: '<p>در دیدار وزرای دفاع دو کشور، توافقات جدیدی امضا شد...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'rejected',
    author: { id: '3', username: 'editor1', fullName: 'فاطمه محمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [mockCategories[3]],
    tags: [],
    viewCount: 0,
    rejectionReason: 'نیاز به بررسی مجدد منابع خبری',
    reviewedBy: { id: '2', username: 'content_manager', fullName: 'علی رضایی', avatar: '/placeholder.svg?height=40&width=40' },
    reviewedAt: '2024-03-09T16:00:00Z',
    createdAt: '2024-03-09T10:00:00Z',
    updatedAt: '2024-03-09T16:00:00Z',
    isBreaking: false,
    isFeatured: false,
    isLive: false,
    summary: 'توافقات جدید دفاعی میان ایران و روسیه',
    readingTimeMinutes: 4,
  },
]

// Weapon Categories
export const mockWeaponCategories: WeaponCategory[] = [
  { id: '1', name: 'موشک‌های بالستیک', nameEn: 'Ballistic Missiles', slug: 'ballistic-missiles', icon: 'rocket', order: 1, weaponCount: 15 },
  { id: '2', name: 'پهپادها', nameEn: 'Drones', slug: 'drones', icon: 'plane', order: 2, weaponCount: 22 },
  { id: '3', name: 'سامانه‌های دفاع هوایی', nameEn: 'Air Defense Systems', slug: 'air-defense', icon: 'shield', order: 3, weaponCount: 12 },
  { id: '4', name: 'شناورها', nameEn: 'Naval Vessels', slug: 'naval-vessels', icon: 'ship', order: 4, weaponCount: 18 },
  { id: '5', name: 'تانک و زره‌پوش', nameEn: 'Tanks & Armored Vehicles', slug: 'tanks', icon: 'tank', order: 5, weaponCount: 14 },
]

// Mock Weapons
export const mockWeapons: Weapon[] = [
  {
    id: '1',
    type: 'arsenal',
    title: 'موشک بالستیک فتاح',
    titleEn: 'Fattah Hypersonic Missile',
    slug: 'fattah-missile',
    excerpt: 'اولین موشک مافوق صوت ایران با قابلیت نفوذ به سپرهای دفاعی',
    content: '<p>موشک فتاح با سرعت مافوق صوت و قابلیت مانور در فاز نهایی...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '1', username: 'admin', fullName: 'محمد احمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [],
    tags: [mockTags[2]],
    viewCount: 25000,
    publishedAt: '2024-02-15T10:00:00Z',
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
    weaponCategory: mockWeaponCategories[0],
    categoryLabelFa: 'موشک‌های بالستیک',
    rangeKm: 1400,
    specifications: {
      'برد': '۱۴۰۰ کیلومتر',
      'سرعت': 'مافوق صوت (ماخ ۱۳-۱۵)',
      'نوع سوخت': 'جامد',
      'کلاهک': 'معمولی',
    },
    manufacturer: 'وزارت دفاع',
    countryOfOrigin: 'ایران',
    yearIntroduced: 2023,
    isOperational: true,
  },
  {
    id: '2',
    type: 'arsenal',
    title: 'پهپاد شاهد ۱۲۹',
    titleEn: 'Shahed 129 Drone',
    slug: 'shahed-129',
    excerpt: 'پهپاد رزمی-شناسایی با قابلیت پرواز طولانی مدت',
    content: '<p>شاهد ۱۲۹ یکی از پیشرفته‌ترین پهپادهای ایرانی است...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '2', username: 'content_manager', fullName: 'علی رضایی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [],
    tags: [mockTags[3]],
    viewCount: 18500,
    publishedAt: '2024-01-20T10:00:00Z',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    weaponCategory: mockWeaponCategories[1],
    categoryLabelFa: 'پهپادها',
    rangeKm: 1700,
    specifications: {
      'برد عملیاتی': '۱۷۰۰ کیلومتر',
      'سقف پرواز': '۷۳۰۰ متر',
      'مدت پرواز': '۲۴ ساعت',
      'ظرفیت بار': '۴۰۰ کیلوگرم',
    },
    manufacturer: 'صنایع هوافضا',
    countryOfOrigin: 'ایران',
    yearIntroduced: 2012,
    isOperational: true,
  },
]

// Martyr Categories
export const mockMartyrCategories: MartyrCategory[] = [
  { id: '1', name: 'شهدای مدافع حرم', nameEn: 'Shrine Defenders Martyrs', slug: 'shrine-defenders', icon: 'heart', order: 1, martyrCount: 145 },
  { id: '2', name: 'شهدای دفاع مقدس', nameEn: 'Sacred Defense Martyrs', slug: 'sacred-defense', icon: 'flag', order: 2, martyrCount: 890 },
  { id: '3', name: 'شهدای هسته‌ای', nameEn: 'Nuclear Scientists Martyrs', slug: 'nuclear-scientists', icon: 'atom', order: 3, martyrCount: 7 },
  { id: '4', name: 'شهدای امنیت', nameEn: 'Security Martyrs', slug: 'security-martyrs', icon: 'shield', order: 4, martyrCount: 56 },
]

// Mock Martyrs
export const mockMartyrs: Martyr[] = [
  {
    id: '1',
    type: 'martyrs',
    title: 'شهید سردار قاسم سلیمانی',
    titleEn: 'Martyr General Qasem Soleimani',
    slug: 'qasem-soleimani',
    excerpt: 'فرمانده نیروی قدس سپاه پاسداران انقلاب اسلامی',
    content: '<p>سردار شهید حاج قاسم سلیمانی، فرمانده نیروی قدس سپاه...</p>',
    biography: 'سردار سلیمانی در سال ۱۳۳۶ در کرمان متولد شد...',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '1', username: 'admin', fullName: 'محمد احمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [],
    tags: [mockTags[0]],
    viewCount: 150000,
    publishedAt: '2024-01-03T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
    martyrCategory: mockMartyrCategories[0],
    birthDate: '1957-03-11',
    martyrdomDate: '2020-01-03',
    birthPlace: 'کرمان',
    martyrdomPlace: 'بغداد، عراق',
    rank: 'سرلشکر',
    unit: 'نیروی قدس سپاه',
    martyrUnitId: '1',
  },
]

export const mockMartyrUnits = [
  { id: '1', name: 'نیروی قدس سپاه', isActive: true },
  { id: '2', name: 'نیروی زمینی ارتش', isActive: true },
  { id: '3', name: 'پدافند هوایی', isActive: true },
]

// Document Categories
export const mockDocumentCategories: DocumentCategory[] = [
  { id: '1', name: 'آیین‌نامه‌ها', nameEn: 'Regulations', slug: 'regulations', icon: 'file-text', order: 1, documentCount: 34 },
  { id: '2', name: 'گزارش‌های سالانه', nameEn: 'Annual Reports', slug: 'annual-reports', icon: 'bar-chart', order: 2, documentCount: 12 },
  { id: '3', name: 'بخش‌نامه‌ها', nameEn: 'Circulars', slug: 'circulars', icon: 'mail', order: 3, documentCount: 67 },
]

export const mockDocumentTypes = [
  { id: '1', code: 'report', name: 'گزارش', isActive: true },
  { id: '2', code: 'video', name: 'ویدئو', isActive: true },
  { id: '3', code: 'book', name: 'کتاب', isActive: true },
]

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: '1',
    type: 'documents',
    title: 'آیین‌نامه نظام وظیفه عمومی',
    titleEn: 'Military Service Regulations',
    slug: 'military-service-regulations',
    excerpt: 'قوانین و مقررات خدمت وظیفه عمومی',
    content: '<p>این آیین‌نامه شامل تمامی قوانین مربوط به خدمت سربازی است...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '1', username: 'admin', fullName: 'محمد احمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [],
    tags: [],
    viewCount: 45000,
    downloadCount: 12000,
    publishedAt: '2024-01-15T00:00:00Z',
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
    documentCategory: mockDocumentCategories[0],
    fileUrl: '/documents/military-service.pdf',
    fileSize: 2500000,
    fileType: 'application/pdf',
    isConfidential: false,
    confidentialityLevel: 'public',
  },
]

// Achievement Categories
export const mockAchievementCategories: AchievementCategory[] = [
  { id: '1', name: 'دستاوردهای فناوری', nameEn: 'Technology Achievements', slug: 'technology', icon: 'cpu', order: 1, achievementCount: 45 },
  { id: '2', name: 'افتخارات نظامی', nameEn: 'Military Honors', slug: 'military-honors', icon: 'award', order: 2, achievementCount: 32 },
  { id: '3', name: 'پیروزی‌های میدانی', nameEn: 'Field Victories', slug: 'field-victories', icon: 'target', order: 3, achievementCount: 28 },
]

// Mock Achievements
export const mockAchievements: Achievement[] = [
  {
    id: '1',
    type: 'achievements',
    title: 'پرتاب موفق ماهواره نور ۳',
    titleEn: 'Successful launch of Noor 3 satellite',
    slug: 'noor-3-satellite',
    excerpt: 'پرتاب موفقیت‌آمیز ماهواره نور ۳ به فضا',
    content: '<p>ماهواره نور ۳ با موفقیت به مدار زمین پرتاب شد...</p>',
    featuredImage: '/placeholder.svg?height=400&width=600',
    status: 'published',
    author: { id: '1', username: 'admin', fullName: 'محمد احمدی', avatar: '/placeholder.svg?height=40&width=40' },
    categories: [],
    tags: [],
    viewCount: 35000,
    publishedAt: '2024-02-20T00:00:00Z',
    createdAt: '2024-02-18T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
    achievementCategory: mockAchievementCategories[0],
    verificationStatus: 'verified',
    targetType: 'air',
    regionFa: 'منطقه مرکزی',
    destroyedTargetsCount: 0,
    strategicGainCount: 3,
    achievementDate: '2024-02-18',
    location: 'پایگاه فضایی امام خمینی',
    participants: ['نیروی هوافضای سپاه'],
  },
]

// Site Settings
export const mockSiteSettings: SiteSettings = {
  id: '1',
  siteName: 'صدای ایران',
  siteNameEn: 'Voice of Iran',
  siteDescription: 'پایگاه اطلاع‌رسانی وزارت دفاع و پشتیبانی نیروهای مسلح',
  siteDescriptionEn: 'Official news portal of Ministry of Defense',
  logo: '/placeholder.svg?height=60&width=200',
  contactEmail: 'info@voiceiran.ir',
  contactPhone: '۰۲۱-۲۲۲۲۲۲۲۲',
  address: 'تهران، میدان ونک، وزارت دفاع',
  socialLinks: {
    telegram: 'https://t.me/voiceiran',
    twitter: 'https://twitter.com/voiceiran',
  },
  maintenanceMode: false,
  updatedAt: '2024-03-01T00:00:00Z',
}

// Organization Profile
export const mockOrganizationProfile: OrganizationProfile = {
  id: '1',
  name: 'وزارت دفاع و پشتیبانی نیروهای مسلح',
  nameEn: 'Ministry of Defense and Armed Forces Logistics',
  description: 'وزارت دفاع مسئول برنامه‌ریزی و هماهنگی امور دفاعی کشور است.',
  mission: 'تأمین امنیت و دفاع از تمامیت ارضی کشور',
  vision: 'دستیابی به بازدارندگی کامل دفاعی',
  logo: '/placeholder.svg?height=100&width=100',
  foundedDate: '1979-04-01',
  headquarters: 'تهران',
  updatedAt: '2024-03-01T00:00:00Z',
}

// Live Stats
export const mockLiveStats: LiveStat[] = [
  { id: '1', label: 'کل اخبار', labelEn: 'Total News', value: 1245, displayValue: '۱,۲۴۵', icon: 'newspaper', order: 1, isActive: true, updatedAt: '2024-03-10T00:00:00Z' },
  { id: '2', label: 'تسلیحات', labelEn: 'Weapons', value: 156, displayValue: '۱۵۶', icon: 'rocket', order: 2, isActive: true, updatedAt: '2024-03-10T00:00:00Z' },
  { id: '3', label: 'شهدا', labelEn: 'Martyrs', value: 1098, displayValue: '۱,۰۹۸', icon: 'heart', order: 3, isActive: true, updatedAt: '2024-03-10T00:00:00Z' },
  { id: '4', label: 'اسناد', labelEn: 'Documents', value: 324, displayValue: '۳۲۴', icon: 'file', order: 4, isActive: true, updatedAt: '2024-03-10T00:00:00Z' },
]

// Banners
export const mockBanners: Banner[] = [
  {
    id: '1',
    title: 'روز نیروی دریایی',
    subtitle: 'گرامیداشت روز نیروی دریایی ارتش',
    image: '/placeholder.svg?height=400&width=1200',
    link: '/news/navy-day',
    linkText: 'بیشتر بخوانید',
    position: 'hero',
    order: 1,
    isActive: true,
    viewCount: 15000,
    clickCount: 2500,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
]

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'info',
    title: 'مطلب جدید برای بررسی',
    message: 'یک مطلب جدید توسط فاطمه محمدی برای بررسی ارسال شده است.',
    link: '/news/3',
    linkText: 'مشاهده',
    isRead: false,
    userId: '1',
    createdAt: '2024-03-10T09:30:00Z',
  },
  {
    id: '2',
    type: 'success',
    title: 'انتشار موفق',
    message: 'مطلب "رونمایی از سامانه جدید دفاع هوایی" با موفقیت منتشر شد.',
    isRead: false,
    userId: '1',
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '3',
    type: 'warning',
    title: 'انتشار زمان‌بندی شده',
    message: '۳ مطلب برای انتشار در ساعت آینده زمان‌بندی شده است.',
    isRead: true,
    userId: '1',
    createdAt: '2024-03-10T08:00:00Z',
    readAt: '2024-03-10T08:15:00Z',
  },
]

// Publish Schedules
export const mockPublishSchedules: PublishSchedule[] = [
  {
    id: '1',
    contentType: 'news',
    contentId: '4',
    contentTitle: 'دیدار فرمانده کل سپاه با رهبر انقلاب',
    scheduledAt: '2024-03-11T10:00:00Z',
    action: 'publish',
    status: 'pending',
    createdBy: 'محمد احمدی',
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-10T11:00:00Z',
  },
]

// SEO Configs
export const mockSeoConfigs: SeoConfig[] = [
  {
    id: '1',
    path: '/',
    metaTitle: 'صدای ایران - پایگاه اطلاع‌رسانی وزارت دفاع',
    metaDescription: 'آخرین اخبار و اطلاعات از وزارت دفاع و پشتیبانی نیروهای مسلح',
    ogTitle: 'صدای ایران',
    ogDescription: 'پایگاه رسمی اطلاع‌رسانی وزارت دفاع',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

// Redirect Rules
export const mockRedirectRules: RedirectRule[] = [
  {
    id: '1',
    sourcePath: '/old-news',
    targetPath: '/news',
    redirectType: 301,
    isActive: true,
    hitCount: 234,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

// API Clients
export const mockApiClients: ApiClient[] = [
  {
    id: '1',
    name: 'اپلیکیشن موبایل',
    description: 'کلاینت اپلیکیشن موبایل صدای ایران',
    clientId: 'mobile-app-001',
    clientType: 'first_party',
    isActive: true,
    rateLimit: 1000,
    rateLimitPeriod: 'minute',
    allowedOrigins: ['https://voiceiran.ir', 'https://app.voiceiran.ir'],
    owners: ['1', '2'],
    requestCount: 125000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
]

export const mockApiKeys = [
  {
    id: '1',
    clientId: '1',
    keyPrefix: 'vra_7hd2',
    isActive: true,
    expiresAt: '2026-12-01T00:00:00Z',
    lastUsedAt: '2026-04-01T08:00:00Z',
  },
]

export const mockApiRateLimits: ApiRateLimit[] = [
  {
    id: '1',
    scope: 'global',
    limitPerMinute: 1200,
    limitPerDay: 500000,
    burstLimit: 200,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
  },
]

// Analytics Dashboard
export const mockAnalyticsDashboard: AnalyticsDashboard = {
  period: 'month',
  totalPageViews: 2450000,
  totalUniqueVisitors: 890000,
  totalContentItems: 2823,
  publishedToday: 12,
  pendingReview: 8,
  visitStats: Array.from({ length: 30 }, (_, i) => ({
    date: `2024-02-${String(i + 1).padStart(2, '0')}`,
    pageViews: Math.floor(Math.random() * 100000) + 50000,
    uniqueVisitors: Math.floor(Math.random() * 40000) + 20000,
    avgSessionDuration: Math.floor(Math.random() * 180) + 60,
    bounceRate: Math.random() * 30 + 20,
  })),
  contentDistribution: [
    { contentType: 'news', contentTypeLabel: 'اخبار', count: 1245, viewCount: 1500000, percentage: 44 },
    { contentType: 'arsenal', contentTypeLabel: 'تسلیحات', count: 156, viewCount: 450000, percentage: 6 },
    { contentType: 'martyrs', contentTypeLabel: 'شهدا', count: 1098, viewCount: 350000, percentage: 39 },
    { contentType: 'documents', contentTypeLabel: 'اسناد', count: 324, viewCount: 150000, percentage: 11 },
  ],
  popularContent: [
    { id: '1', title: 'رونمایی از سامانه جدید دفاع هوایی باور ۳۷۳', contentType: 'news', viewCount: 125000, uniqueViews: 98000, avgReadTime: 245, publishedAt: '2024-03-10T10:00:00Z' },
    { id: '2', title: 'موشک بالستیک فتاح', contentType: 'arsenal', viewCount: 98000, uniqueViews: 76000, avgReadTime: 320, publishedAt: '2024-02-15T10:00:00Z' },
    { id: '3', title: 'شهید سردار قاسم سلیمانی', contentType: 'martyrs', viewCount: 150000, uniqueViews: 120000, avgReadTime: 480, publishedAt: '2024-01-03T00:00:00Z' },
  ],
  topReferrers: [
    { source: 'Google', visits: 450000 },
    { source: 'Telegram', visits: 280000 },
    { source: 'Direct', visits: 120000 },
    { source: 'Twitter', visits: 40000 },
  ],
  deviceBreakdown: [
    { device: 'موبایل', percentage: 65 },
    { device: 'دسکتاپ', percentage: 28 },
    { device: 'تبلت', percentage: 7 },
  ],
  topCountries: [
    { country: 'ایران', flag: '🇮🇷', percentage: 76 },
    { country: 'عراق', flag: '🇮🇶', percentage: 8 },
    { country: 'لبنان', flag: '🇱🇧', percentage: 5 },
    { country: 'ترکیه', flag: '🇹🇷', percentage: 4 },
    { country: 'افغانستان', flag: '🇦🇫', percentage: 3 },
    { country: 'روسیه', flag: '🇷🇺', percentage: 2 },
    { country: 'سوریه', flag: '🇸🇾', percentage: 1 },
    { country: 'آلمان', flag: '🇩🇪', percentage: 1 },
  ],
}

export const mockLanguages: LanguageSetting[] = [
  {
    id: '1',
    code: 'fa',
    name: 'فارسی',
    isDefault: true,
    isActive: true,
    direction: 'rtl',
    calendarSystem: 'jalali',
    dateFormat: 'YYYY/MM/DD',
    numberFormat: 'fa-IR',
    fallbackLanguage: 'en',
  },
  {
    id: '2',
    code: 'en',
    name: 'English',
    isDefault: false,
    isActive: true,
    direction: 'ltr',
    calendarSystem: 'gregorian',
    dateFormat: 'YYYY-MM-DD',
    numberFormat: 'en-US',
  },
]
