# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("review", "در انتظار بازبینی"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="arsenal/covers/%Y/%m/%d/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "range_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="برد (کیلومتر)",
                    ),
                ),
                (
                    "name_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام فارسی"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "type_label_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نوع فارسی"
                    ),
                ),
                (
                    "type_label_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نوع انگلیسی"
                    ),
                ),
                (
                    "category_label_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="برچسب دسته فارسی"
                    ),
                ),
                (
                    "category_label_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="برچسب دسته انگلیسی"
                    ),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, verbose_name="توضیحات فارسی"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                (
                    "summary_fa",
                    models.TextField(blank=True, verbose_name="خلاصه فارسی"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="خلاصه انگلیسی"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "category"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weapons",
                        to="taxonomy.term",
                        verbose_name="دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسلیح",
                "verbose_name_plural": "تسلیحات",
            },
        ),
        migrations.CreateModel(
            name="WeaponSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="کلید مشخصه")),
                ("value", models.CharField(max_length=255, verbose_name="مقدار")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="واحد"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="عمومی")),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="arsenal.weapon",
                        verbose_name="تسلیح",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه تسلیح",
                "verbose_name_plural": "مشخصه های تسلیحات",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="weapon",
            index=models.Index(
                fields=["status", "published_at"], name="arsenal_wea_status_0e851a_idx"
            ),
        ),
    ]
