# Generated by Django 5.2.8 on 2026-04-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="permission_profile",
        ),
        migrations.AddField(
            model_name="user",
            name="access_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.accessprofile",
                verbose_name="پروفایل دسترسی",
            ),
        ),
        migrations.DeleteModel(
            name="PermissionProfile",
        ),
    ]
