# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Martyr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="martyrs/profiles/%Y/%m/%d/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "martyrdom_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شهادت"),
                ),
                (
                    "martyrdom_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="محل شهادت"
                    ),
                ),
                (
                    "name_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام فارسی"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان فارسی"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                (
                    "biography_fa",
                    models.TextField(blank=True, verbose_name="زندگی نامه فارسی"),
                ),
                (
                    "biography_en",
                    models.TextField(blank=True, verbose_name="زندگی نامه انگلیسی"),
                ),
                (
                    "short_bio_fa",
                    models.TextField(blank=True, verbose_name="خلاصه زندگی نامه فارسی"),
                ),
                (
                    "short_bio_en",
                    models.TextField(
                        blank=True, verbose_name="خلاصه زندگی نامه انگلیسی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("review", "در انتظار بازبینی"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "شهید",
                "verbose_name_plural": "شهدا",
            },
        ),
        migrations.CreateModel(
            name="MartyrUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام انگلیسی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "یگان شهید",
                "verbose_name_plural": "یگان های شهدا",
            },
        ),
        migrations.CreateModel(
            name="MartyrAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "martyr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="martyrs.martyr",
                        verbose_name="شهید",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستاورد شهید",
                "verbose_name_plural": "دستاوردهای شهدا",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="martyr",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="martyrs",
                to="martyrs.martyrunit",
                verbose_name="یگان",
            ),
        ),
        migrations.AddIndex(
            model_name="martyr",
            index=models.Index(
                fields=["status", "published_at"], name="martyrs_mar_status_6ffab9_idx"
            ),
        ),
    ]
