# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام سازمان")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام انگلیسی سازمان"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="آدرس"),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="آدرس انگلیسی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="تلفن"),
                ),
                ("website", models.URLField(blank=True, verbose_name="وب سایت")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core/logos/%Y/%m/%d/",
                        verbose_name="لوگو",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل سازمان",
                "verbose_name_plural": "پروفایل سازمان",
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "site_name",
                    models.CharField(max_length=200, verbose_name="نام سایت"),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام انگلیسی سایت"
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="fa", max_length=5, verbose_name="زبان پیش فرض"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Tehran", max_length=64, verbose_name="منطقه زمانی"
                    ),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(default=False, verbose_name="حالت نگهداری"),
                ),
                (
                    "maintenance_message",
                    models.TextField(blank=True, verbose_name="پیام نگهداری"),
                ),
            ],
            options={
                "verbose_name": "تنظیم سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="متن")),
                ("body_en", models.TextField(blank=True, verbose_name="متن انگلیسی")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعاتی"),
                            ("warning", "هشدار"),
                            ("critical", "بحرانی"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="سطح",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_banners",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر اعلان",
                "verbose_name_plural": "بنرهای اعلان",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("legal", "حقوقی"),
                            ("policy", "سیاست"),
                            ("about", "درباره"),
                            ("help", "راهنما"),
                        ],
                        default="legal",
                        max_length=20,
                        verbose_name="نوع صفحه",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="متن")),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="متن انگلیسی"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه ثابت",
                "verbose_name_plural": "صفحات ثابت",
                "indexes": [
                    models.Index(
                        fields=["page_type", "is_published"],
                        name="core_static_page_ty_a03308_idx",
                    )
                ],
            },
        ),
    ]
