# Generated by Django 5.2.8 on 2026-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "hero_title_fa",
                    models.CharField(
                        default="صدای ایران",
                        max_length=255,
                        verbose_name="عنوان هیرو فارسی",
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        blank=True,
                        default="Voice of Iran",
                        max_length=255,
                        verbose_name="عنوان هیرو انگلیسی",
                    ),
                ),
                (
                    "hero_description_fa",
                    models.TextField(
                        default="روایت مستند از شهدا، اخبار، تسلیحات و آرشیو اسناد.",
                        verbose_name="توضیح هیرو فارسی",
                    ),
                ),
                (
                    "hero_description_en",
                    models.TextField(
                        blank=True,
                        default="Documented narratives of martyrs, news, weapons, and archive collections.",
                        verbose_name="توضیح هیرو انگلیسی",
                    ),
                ),
                (
                    "latest_news_title_fa",
                    models.CharField(
                        default="آخرین اخبار",
                        max_length=255,
                        verbose_name="عنوان بخش خبر فارسی",
                    ),
                ),
                (
                    "latest_news_title_en",
                    models.CharField(
                        blank=True,
                        default="Latest News",
                        max_length=255,
                        verbose_name="عنوان بخش خبر انگلیسی",
                    ),
                ),
                (
                    "featured_weapons_title_fa",
                    models.CharField(
                        default="تسلیحات ویژه",
                        max_length=255,
                        verbose_name="عنوان بخش تسلیحات فارسی",
                    ),
                ),
                (
                    "featured_weapons_title_en",
                    models.CharField(
                        blank=True,
                        default="Featured Weapons",
                        max_length=255,
                        verbose_name="عنوان بخش تسلیحات انگلیسی",
                    ),
                ),
                (
                    "featured_documents_title_fa",
                    models.CharField(
                        default="مستندات ویژه",
                        max_length=255,
                        verbose_name="عنوان بخش مستندات فارسی",
                    ),
                ),
                (
                    "featured_documents_title_en",
                    models.CharField(
                        blank=True,
                        default="Featured Documents",
                        max_length=255,
                        verbose_name="عنوان بخش مستندات انگلیسی",
                    ),
                ),
                (
                    "featured_martyrs_title_fa",
                    models.CharField(
                        default="شهدای ویژه",
                        max_length=255,
                        verbose_name="عنوان بخش شهدا فارسی",
                    ),
                ),
                (
                    "featured_martyrs_title_en",
                    models.CharField(
                        blank=True,
                        default="Featured Martyrs",
                        max_length=255,
                        verbose_name="عنوان بخش شهدا انگلیسی",
                    ),
                ),
                (
                    "view_all_label_fa",
                    models.CharField(
                        default="مشاهده همه",
                        max_length=100,
                        verbose_name="برچسب مشاهده همه فارسی",
                    ),
                ),
                (
                    "view_all_label_en",
                    models.CharField(
                        blank=True,
                        default="View all",
                        max_length=100,
                        verbose_name="برچسب مشاهده همه انگلیسی",
                    ),
                ),
                (
                    "empty_label_fa",
                    models.CharField(
                        default="موردی برای نمایش وجود ندارد.",
                        max_length=150,
                        verbose_name="برچسب خالی فارسی",
                    ),
                ),
                (
                    "empty_label_en",
                    models.CharField(
                        blank=True,
                        default="No items are available.",
                        max_length=150,
                        verbose_name="برچسب خالی انگلیسی",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "محتوای صفحه اصلی",
                "verbose_name_plural": "محتواهای صفحه اصلی",
            },
        ),
    ]
