# Generated by Django 6.0.3 on 2026-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_homepagecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="drills_label_en",
            field=models.CharField(
                blank=True,
                default="Drills",
                max_length=120,
                verbose_name="برچسب رزمایش انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="drills_label_fa",
            field=models.CharField(
                default="رزمایش\u200cها",
                max_length=120,
                verbose_name="برچسب رزمایش فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="drills_value",
            field=models.PositiveIntegerField(default=156, verbose_name="عدد رزمایش"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_background_image",
            field=models.URLField(
                blank=True,
                default="https://picsum.photos/seed/iran-hero/1920/1080",
                verbose_name="تصویر پس زمینه هیرو",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_live_badge_en",
            field=models.CharField(
                blank=True,
                default="LIVE",
                max_length=100,
                verbose_name="برچسب زنده هیرو انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_live_badge_fa",
            field=models.CharField(
                default="زنده", max_length=100, verbose_name="برچسب زنده هیرو فارسی"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_primary_action_en",
            field=models.CharField(
                blank=True,
                default="Watch Report",
                max_length=120,
                verbose_name="دکمه اصلی هیرو انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_primary_action_fa",
            field=models.CharField(
                default="تماشای گزارش",
                max_length=120,
                verbose_name="دکمه اصلی هیرو فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_secondary_action_en",
            field=models.CharField(
                blank=True,
                default="Learn More",
                max_length=120,
                verbose_name="دکمه ثانویه هیرو انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_secondary_action_fa",
            field=models.CharField(
                default="اطلاعات بیشتر",
                max_length=120,
                verbose_name="دکمه ثانویه هیرو فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="intercepted_label_en",
            field=models.CharField(
                blank=True,
                default="Intercepted Targets",
                max_length=120,
                verbose_name="برچسب رهگیری انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="intercepted_label_fa",
            field=models.CharField(
                default="اهداف رهگیری\u200cشده",
                max_length=120,
                verbose_name="برچسب رهگیری فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="intercepted_value",
            field=models.PositiveIntegerField(default=2341, verbose_name="عدد رهگیری"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="live_stats_title_en",
            field=models.CharField(
                blank=True,
                default="Live Stats",
                max_length=255,
                verbose_name="عنوان آمار انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="live_stats_title_fa",
            field=models.CharField(
                default="آمار لحظه\u200cای",
                max_length=255,
                verbose_name="عنوان آمار فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="martyrs_quote_en",
            field=models.CharField(
                blank=True,
                default='"Do not consider those slain in God\'s way as dead; they are alive."',
                max_length=255,
                verbose_name="نقل قول شهدا انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="martyrs_quote_fa",
            field=models.CharField(
                default="«و لا تحسبن الذین قتلوا فی سبیل الله امواتا بل احیاء»",
                max_length=255,
                verbose_name="نقل قول شهدا فارسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="operations_label_en",
            field=models.CharField(
                blank=True,
                default="Successful Operations",
                max_length=120,
                verbose_name="برچسب عملیات انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="operations_label_fa",
            field=models.CharField(
                default="عملیات موفق", max_length=120, verbose_name="برچسب عملیات فارسی"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="operations_value",
            field=models.PositiveIntegerField(default=847, verbose_name="عدد عملیات"),
        ),
    ]
