# Generated by Django 5.2.8 on 2026-04-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_homepagecontent_drills_label_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="hero_background_image",
            field=models.URLField(
                blank=True,
                default="/images/placeholder-media.svg",
                verbose_name="تصویر پس زمینه هیرو",
            ),
        ),
    ]
