# Generated by Django 5.2.8 on 2026-04-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_homepagecontent_hero_background_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "key",
                    models.SlugField(max_length=64, unique=True, verbose_name="کلید"),
                ),
                (
                    "label_fa",
                    models.CharField(max_length=120, verbose_name="عنوان فارسی"),
                ),
                (
                    "label_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0, verbose_name="مقدار")),
                (
                    "icon_key",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کلید آیکن"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "آمار لحظه\u200cای",
                "verbose_name_plural": "آمارهای لحظه\u200cای",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
