# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه محتوا"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=120, verbose_name="منبع"),
                ),
                (
                    "device",
                    models.CharField(blank=True, max_length=60, verbose_name="دستگاه"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="کشور"),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان مشاهده"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید صفحه",
                "verbose_name_plural": "بازدید صفحات",
                "indexes": [
                    models.Index(
                        fields=["viewed_at"], name="analytics_p_viewed__6302cc_idx"
                    )
                ],
            },
        ),
    ]
