# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="عمومی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
            ],
            options={
                "verbose_name": "مجموعه مستند",
                "verbose_name_plural": "مجموعه های مستند",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="کد نوع"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام انگلیسی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "نوع مستند",
                "verbose_name_plural": "انواع مستند",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("review", "در انتظار بازبینی"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="documents/thumbnails/%Y/%m/%d/",
                        verbose_name="تصویر بندانگشتی",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="تعداد بازدید"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="تعداد دانلود"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت زمان (ثانیه)"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد صفحات"
                    ),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد آیتم"
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان فارسی"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, verbose_name="توضیحات فارسی"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                (
                    "summary_fa",
                    models.TextField(blank=True, verbose_name="خلاصه فارسی"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="خلاصه انگلیسی"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="documents.documentcollection",
                        verbose_name="مجموعه ها",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documenttype",
                        verbose_name="نوع مستند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند",
                "verbose_name_plural": "مستندات",
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/files/%Y/%m/%d/", verbose_name="فایل"
                    ),
                ),
                (
                    "file_role",
                    models.CharField(
                        choices=[
                            ("primary", "اصلی"),
                            ("preview", "پیش نمایش"),
                            ("subtitle", "زیرنویس"),
                            ("attachment", "پیوست"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="نقش فایل",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="فایل اصلی"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="documents.document",
                        verbose_name="مستند",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_files",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل مستند",
                "verbose_name_plural": "فایل های مستند",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "published_at"], name="documents_d_status_ac1793_idx"
            ),
        ),
    ]
