# Generated by Django 5.2.8 on 2026-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="سال")),
                (
                    "title_fa",
                    models.CharField(max_length=255, verbose_name="عنوان فارسی"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان انگلیسی"
                    ),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, verbose_name="توضیحات فارسی"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات انگلیسی"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "رویداد تایم لاین مستندات",
                "verbose_name_plural": "رویدادهای تایم لاین مستندات",
                "ordering": ["-year", "sort_order", "id"],
            },
        ),
    ]
