# Generated by Django 5.2.8 on 2026-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documenttimelineevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="meta_description_en",
            field=models.TextField(blank=True, verbose_name="توضیحات متا انگلیسی"),
        ),
        migrations.AddField(
            model_name="document",
            name="meta_description_fa",
            field=models.TextField(blank=True, verbose_name="توضیحات متا فارسی"),
        ),
        migrations.AddField(
            model_name="document",
            name="meta_title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان متا انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="meta_title_fa",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان متا فارسی"
            ),
        ),
    ]
