# Generated by Django 5.2.8 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=5, unique=True, verbose_name="کد زبان"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام زبان")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="پیش فرض"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "direction",
                    models.CharField(
                        choices=[("rtl", "راست به چپ"), ("ltr", "چپ به راست")],
                        default="rtl",
                        max_length=3,
                        verbose_name="جهت نوشتار",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
            ],
            options={
                "verbose_name": "زبان",
                "verbose_name_plural": "زبان ها",
            },
        ),
        migrations.CreateModel(
            name="LanguageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="%Y-%m-%d", max_length=64, verbose_name="فرمت تاریخ"
                    ),
                ),
                (
                    "number_format",
                    models.CharField(
                        default="#,##0.###", max_length=64, verbose_name="فرمت عدد"
                    ),
                ),
                (
                    "calendar_system",
                    models.CharField(
                        default="gregorian", max_length=32, verbose_name="نوع تقویم"
                    ),
                ),
                (
                    "fallback_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for",
                        to="localization.language",
                        verbose_name="زبان جایگزین",
                    ),
                ),
                (
                    "language",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_config",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیکربندی زبان",
                "verbose_name_plural": "پیکربندی\u200cهای زبان",
            },
        ),
        migrations.CreateModel(
            name="UnifiedTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(max_length=40, verbose_name="نوع منبع"),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(verbose_name="شناسه منبع"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="عنوان"),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="خلاصه کوتاه")),
                ("summary", models.TextField(blank=True, verbose_name="خلاصه")),
                ("content", models.TextField(blank=True, verbose_name="متن")),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="فیلدهای اضافی"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_translations",
                        to="localization.language",
                        verbose_name="زبان",
                    ),
                ),
            ],
            options={
                "verbose_name": "ترجمه یکپارچه",
                "verbose_name_plural": "ترجمه\u200cهای یکپارچه",
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="localizatio_source__6985dc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_id", "language"),
                        name="uq_unified_translation_source_language",
                    )
                ],
            },
        ),
    ]
