# Generated by Django 5.2.8 on 2026-04-05 10:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_from_language_config(apps, schema_editor):
    Language = apps.get_model("localization", "Language")
    LanguageConfig = apps.get_model("localization", "LanguageConfig")
    for cfg in LanguageConfig.objects.select_related("language").all():
        Language.objects.filter(pk=cfg.language_id).update(
            date_format=cfg.date_format,
            number_format=cfg.number_format,
            calendar_system=cfg.calendar_system,
            fallback_language_id=cfg.fallback_language_id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("localization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="calendar_system",
            field=models.CharField(
                default="gregorian", max_length=32, verbose_name="نوع تقویم"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="date_format",
            field=models.CharField(
                default="%Y-%m-%d", max_length=64, verbose_name="فرمت تاریخ"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="fallback_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fallback_for_languages",
                to="localization.language",
                verbose_name="زبان جایگزین",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="number_format",
            field=models.CharField(
                default="#,##0.###", max_length=64, verbose_name="فرمت عدد"
            ),
        ),
        migrations.RunPython(backfill_from_language_config, migrations.RunPython.noop),
    ]
